services:
  db:
    container_name: filmes_para_assistir_db
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5332:5432"
    networks:
      - db
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "postgres"

  app:
    container_name: filmes_para_assistir_app
    depends_on:
      - db
    environment:
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
    networks:
      - db


networks:
  db:
    driver: bridge