// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Filme struct {
	ID        int64
	Nome      string
	Assistido bool
	TipoID    int64
	CreatedAt pgtype.Date
}

type Tipo struct {
	ID   int64
	Nome string
}
